txn_box:

- when: creq
  do:
    var<Delain>: creq-host

- when: preq
  do:
  - preq-field<TxnBox>: "Delain"
  - debug: var<Delain>

- when: prsp
  do:
  - prsp-field<Access-Control-Allow-Origin>: NULL
  - debug: "Data from remap: {var<Remap>}"

